### ISSUE TITLE
cli segfaults on power with rhel & centos

### ISSUE THREAD

**Issue by clnperez** [NVIDIA/libnvidia-container#25] opened 2018-05-30 22:03 UTC
This is kind of a question-issue. I set up the runtime on a RHEL 7.5 system, but then when I tried using it via docker commands, I got a segfault in the cli. So, running just the cli, at one time (I thought) I at least got some usage instructions. Now just a segfault. Could it be that a prereq is checked for first? It doesn't look like that's the case.

```
$ /usr/bin/nvidia-container-cli --help
Segmentation fault
```

I built a debug version of the cli and attached gdb to it. But putting my first breakpoint at `main` hit this too, so it's pretty immediate, which is weird. 

If this is not expected, I can provide more detail of course.

**Comment by flx42** [comment] 2018-05-30 22:16
Is that ppc64le?

**Comment by 3XX0** [comment] 2018-05-30 22:18
Did you install it from the repository?
Can you check that the CLI and the library come from the same build:

run `ldd /usr/bin/nvidia-container-cli`, then execute the path to `libnvidia-container.so.1` and check that the `build revision` matches `/usr/bin/nvidia-container-cli -V` (or ` strings /usr/bin/nvidia-container-cli | grep <BUILD_ID_HASH>` if this segfaults too)

**Comment by clnperez** [comment] 2018-05-31 15:17
@3XX0 yah, I did.

for a centos recreate i installed a new vm and installed everything from repos. 

and yes, running libnvidia-container.so.1 segfaults too, so here's the build info via strings for those two files:

`nvidia-container-cli`:
version: %s
1.0.0
build date: %s
2018-04-30T10:06+0000
build revision: %s
163054a04b21c4455c8cae7e47873d9f2a091f55
build compiler: %s
gcc 4.8.5 20150623 (Red Hat 4.8.5-16)
build platform: %s
ppc64le

'strings /lib64/libnvidia-container.so.1 `
version: %s
1.0.0
build date: %s
2018-04-30T10:06+0000
build revision: %s
163054a04b21c4455c8cae7e47873d9f2a091f55
build compiler: %s
gcc 4.8.5 20150623 (Red Hat 4.8.5-16)
build platform: %s
ppc64le

so looks like they're from the same build.

**Comment by 3XX0** [comment] 2018-06-01 20:08
Weird, can you check that the path to the interpreter is actually correct:

`objdump -j .interp -d /lib64/libnvidia-container.so.1`

I'll try to get my hands on a PPC machine see if I can reproduce

**Comment by clnperez** [comment] 2018-06-04 01:36
```
$ objdump -j .interp -d  /lib64/libnvidia-container.so.1

/lib64/libnvidia-container.so.1:     file format elf64-powerpcle


Disassembly of section .interp:

0000000000030a78 <.interp>:
   30a78:       2f 6c 69 62     ori     r9,r19,27695
   30a7c:       36 34 2f 6c     xoris   r15,r1,13366
   30a80:       64 36 34 2e     cmpdi   cr4,r20,13924
   30a84:       73 6f 2e 32     addic   r17,r14,28531
        ...
```
:/

**Comment by 3XX0** [comment] 2018-06-04 02:39
Looks like on power you need `-s` instead of `-d`.
The hexa translates to `/lib64/ld64.so.2`

**Comment by clnperez** [comment] 2018-06-04 03:09
:D 

Well, then, that looks sane:

```
$ ls -lah /lib64/ld64.so.2 
lrwxrwxrwx. 1 root root 10 May 29 18:14 /lib64/ld64.so.2 -> ld-2.17.so
]$ ls -lah /lib64/ld-2.17.so 
-rwxr-xr-x. 1 root root 217K Apr 10 04:39 /lib64/ld-2.17.so
```

**Comment by 3XX0** [comment] 2018-06-05 19:03
@clnperez Any way I can get my hands on a VM somewhere?
I suppose I don't need GPUs to reproduce, so it would speed up the process rather than waiting for one internally.

**Comment by maximecpe** [comment] 2018-06-05 19:39
Hi,
I confirm, I have exactly the same problem on my power with RHEL 7.5. Running libnvidia-container.so.1 segfaults too...

**Comment by clnperez** [comment] 2018-06-05 21:32
@3XX0 here are some options: https://developer.ibm.com/linuxonpower/cloud-resources/
The *fastest* would be SiteOx. The most cost-effective (free!) would be OSU or PDP. LMK if you have any questions. I can set you up with another OSU VM, or, if you request one yourself, put me as the contact/sponsor.

**Comment by maximecpe** [comment] 2018-06-06 18:54
Here is what `dmesg` returns:

` kernel: libnvidia-conta[22745]: unhandled signal 11 at 00000001302f0000 nip 00003fff78511214 lr 00003fff78505648 code 30002`

**Comment by 3XX0** [comment] 2018-06-06 21:30
So I managed to reproduce with [this base](https://github.com/CentOS/sig-cloud-instance-images/tree/CentOS-7-ppc64le/docker) which seems to indicate there has been an ABI break since then (the new one being [here](https://github.com/CentOS/sig-cloud-instance-images/tree/CentOS-7ppc64le/docker).

@clnperez any idea?

**Comment by maximecpe** [comment] 2018-06-07 18:43
@clnperez  Is there another way to build a container with cuda and nvidia drivers for this architecture (ppc64le) with RHEL 7.5?

**Comment by maximecpe** [comment] 2018-06-11 19:49
Any solution guys ?

**Comment by 3XX0** [comment] 2018-06-12 00:59
This should be fixed in RC 2. Feel free to reopen if that's not the case.

**Closed by 3XX0** 2018-06-12 00:59 UTC
