### ISSUE TITLE
https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list contains 18.04 URLs

### ISSUE THREAD

**Issue by ewaldmire** [NVIDIA/libnvidia-container#139] opened 2021-06-18 20:50 UTC
https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list currently contains:

deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /

...so it's installing 18.04 packages on 20.04 systems.   Is this intentional?

**Comment by ewaldmire** [comment] 2021-06-18 21:27
Also - even if manually s/18/20/g the nvidia-docker.list file and try to install nvidia-container-toolkit (after apt clean && apt update) - it still installs packages labelled "bionic" on my focal machine:

```
root@focal:[/etc/apt/sources.list.d]: apt list --installed | grep bionic

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnvidia-container-tools/bionic,now 1.4.0-1 amd64 [installed,automatic]
libnvidia-container1/bionic,now 1.4.0-1 amd64 [installed,automatic]
nvidia-container-toolkit/bionic,now 1.5.1-1 amd64 [installed]
root@focal:[/etc/apt/sources.list.d]: 

```

**Comment by ewaldmire** [comment] 2021-06-19 00:53
Looks like this is a duplicate of https://github.com/NVIDIA/libnvidia-container/issues/112

...but still seems odd to do for an LTS release of Ubuntu?

**Comment by elezar** [comment] 2021-06-21 08:25
The packages for Ubuntu 18.04 and 20.04 are the same and as such we don't release them separately. As you mention, this does cause some confusion for users seeing the `18.04` in the default list.

We are looking at how to improve this going forward.

Since this is expected behaviour (as also stated in #112), I am closing this issue for the time being.

**Closed by elezar** 2021-06-21 08:25 UTC
